//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelReservation.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleInitial { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phoneNum { get; set; }
        public string userName { get; set; }
        public string userPass { get; set; }
    }
}
